#!/usr/bin/env python3
from database import session, RSIDCitation
from sys import argv
import progressbar


help_text = """USAGE: ./generate_vcf </path/to/output/file>"""

if len(argv) != 2 or argv[1] in ("help", "--help", "-h"):
    print(help_text)
else:
    output_file = open(argv[1], "w")
    output_text = ""
    rsid_citations = session.query(RSIDCitation).order_by(RSIDCitation.rsid).all()
    count = 0
    with progressbar.ProgressBar(max_value=len(rsid_citations)) as bar:
        for rsid_citation in rsid_citations:
            count += 1
            for vcf_tuple in rsid_citation.vcf_data():
                output_file.write("{}\t{}\t{}\n".format(
                    str(vcf_tuple[0]).strip(),
                    str(vcf_tuple[1]).strip(),
                    vcf_tuple[2].strip()
                ))
            bar.update(count)
