#!/usr/bin/env python3
from database import initialize_database, load_all_data, load_data_not_present, update_data
from sys import argv


help_text = """USAGE:
./manage_db <command>
 commands:
    - initialize    creates tables in database, should only be run once
    - load          loads all snp cited articles from pubmed
    - resume        if load fails partway through, loads any articles that were not added to the database
    - update        loads any articles that have been added/modified since latest update
"""

def help():
    print(help_text)


commands = {
    "--help": help,
    "-h": help,
    "initialize": initialize_database,
    "load": load_all_data,
    "resume": load_data_not_present,
    "update": update_data,
}

if len(argv) == 2 and argv[1] in commands:
    commands[argv[1]]()
else:
    help()